### ISSUE TITLE
Found more issues in your PSM

### ISSUE THREAD

**Issue by crtprkppns** [krabo0om/pauloBlaze#3]
When I in my sub-design replace my PSM with yours I get strange, faulty results.

![PauloBlaze_error_coming_out_of_sleep](https://user-images.githubusercontent.com/57508706/68435605-fccc9700-01bb-11ea-9966-5614f8a31379.jpg)

I noticed that the PauloBlaze is not self starting, you need to assert the reset for the PSM to start. In my design I use the sleep signal. In the Modelsim image you can see the result. Prior to sleep it also executes the instruction **after** a jump instruction. Exiting sleep at the return instruction a bad address is pulled from the stack. Actually a wrong address is placed on the stack, PC+2 instead of PC+1. I reviewed the file _program_counter.vhd_ but can't detect the carry- zero- and regbank-flags that must also be placed on the stack together with the return address, which is essential in case of an interrupt. An _outputk_ instruction strobes the _k_write_strobe_ as well as the _write_strobe_, it should only effect the former.

**Comment by krabo0om** [comment]
Thank you for reporting those three (?) problems. The last one (_write_strobe_ vs _k_write_strobe_) is tracked by issue #4.

About the sleep: Can you share a design where this problem can be reproduced? If not, could you prepare a minimal design instead?

Should we track the need for a reset in a separate issue? If the PauloBlaze is not a drop-in replacement, we should track it.

**Comment by krabo0om** [comment]
#4 is fixed with  e94f936

**Comment by krabo0om** [comment]
Hi @crtprkppns ,
I worked on the sleep and jump/return issue. Now it should be much better.
I further working on interrupt handling. Can you please test it?

The flags are handled within the ALU. It has preserve/restore inputs (driven by the decoder), the flags are not pushed onto any sort of stack.

**Comment by crtprkppns** [comment]
Hello Paul,

You are right about the flags using the interrupt. Since only one interrupt can be handled at a time these flags can reside anywhere else.

I've tested your new design files. There still seems to be a small error regarding the **k_write_strobe** pin. I took the liberty to adjust some code.

![modified_source_outputk](https://user-images.githubusercontent.com/57508706/69376576-cd815400-0caa-11ea-8f19-b64d4047bb67.jpg)

After the modification the simulator produced:

![modified_outputk](https://user-images.githubusercontent.com/57508706/69376630-e853c880-0caa-11ea-8585-7ec16ca8e302.jpg)

Now your PSM seems to work fine, even the sleep- and interrupt-input are okay, according to Modelsim. After simulation I always run my code through a synthesizer, i.e. Vivado or Quartus.
These tools are very helpful and produce different messages. 

![Quartus_information](https://user-images.githubusercontent.com/57508706/69377352-5f3d9100-0cac-11ea-9858-97c5215f7310.jpg)

As you can see it fails to convert the LUTRAM for the registers, scratchpad and stack memory. 
I selected a Stratix 4 as target device. These series have MLAB memory, comparable with Xilinx LUTRAM. Synchronous write and asynchronous read.
Some other lower-end FPGA's like MAX-10 don't even have MLAB/LUTRAM memory. I guess implementing PauloBlaze will then be no option.

![Quartus_utilization](https://user-images.githubusercontent.com/57508706/69377772-3cf84300-0cad-11ea-8469-e676cd4e02c8.jpg)

Best regards, Christopher
